using CsvHelper;

public class Prescriptions
{
    public List<string> Prescription = new List<string>() {
        $"OpitAlliance CONSULTATIONS Docteur Frank BECQUET CHIRURGIE OCULAIRE2-4 route de Paris 44300 NANTES N° 44 1 703626 RPPS 10000601426 Secteur 2 SELARL OPHTALLIANCE secretaire.becquet @ophtalliance.fr CHIRURGIE-Clinique Jules Verne 2-4 route de Paris 44300 NANTES 02 28 44 33 73 Nantes, le 17/08/2023 ORDONNANCE DE TRAIΤΕΜΕΝΤ Monsieur BONAPARTE Napoléon Oeil droit {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration} TRAITEMENT A RENOUVELER PENDANT {PatternPrescriptions.DrugDuration} BADAN BODY-CO-IM BOK BRESSON OUR COURTINDA DIACONESCU GUYDMARCH A HENRY-EHERMOURT-JADE JOUBERT LABROUSSE LE LE ROUKC-B LEROY A MARIERAS CMEYNIEL MU LONESM-M. PETRESCU E SAMSON-ME SANTIAGO K THOMAS En cas d'urgence de nuit ou le week-end, veuillez appeler le 15 Prenez rendez-vous en quelques clics sur www.doctolib.fr ou www.ophtalliance.fr",

        $"Ordonnance bizone 1446501 Articles L. 322-3, 3 кг. 1. 324-див. 161-45 da Conde de la sé Identification du prescripteur Dr Frank BECQUET 2 route de Paris 44300 Nantes Identification de la structure FINESS SIRET 10000601426 441703626 Napoléon BONAPARTE 1127933123568 Le 31/08/2023 Prescriptions relatives au traitement de l'affection de longue durée reconnue (liste ou bors liste (AFFECTION EXONÉRANTE Oeil droit {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration} TRAITEMENT A RENOUVELER PENDANT {PatternPrescriptions.DrugDuration} V Prescriptions SANS RAPPORT avec l'affection de langue durée (MALADIES INTERCURRENTES) Quiconque se rend coupable de fraude ou de fausse déclaration est passible de pénalités financières, d'amende evou d'emprisonnement (articles 313-1, 441-1 441-6 du Code pénal, articles L.114-13 et L. 162-1-14 da Code de la sécurité sociale). S3321",

        $"Ordonnance bizone 1446501 Articles L. 322-3, 3 кг. 1. 324-див. 161-45 da Conde de la sé Identification du prescripteur Dr Frank BECQUET 2 route de Paris 44300 Nantes Identification de la structure FINESS SIRET 10000601426 441703626 Napoléon BONAPARTE 1127933123568 Le 31/08/2023 Prescriptions relatives au traitement de l'affection de longue durée reconnue (liste ou bors liste (AFFECTION EXONÉRANTE Oeil droit {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration} TRAITEMENT A RENOUVELER PENDANT {PatternPrescriptions.DrugDuration} V Prescriptions SANS RAPPORT avec l'affection de langue durée (MALADIES INTERCURRENTES) Oeil droit {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration} TRAITEMENT A RENOUVELER PENDANT {PatternPrescriptions.DrugDuration} Quiconque se rend coupable de fraude ou de fausse déclaration est passible de pénalités financières, d'amende evou d'emprisonnement (articles 313-1, 441-1 441-6 du Code pénal, articles L.114-13 et L. 162-1-14 da Code de la sécurité sociale). S3321",

        $"Ordonnance bizone 1446501 Articles L. 322-3, 3 кг. 1. 324-див. 161-45 da Conde de la sé Identification du prescripteur Dr Frank BECQUET 2 route de Paris 44300 Nantes Identification de la structure FINESS SIRET 10000601426 441703626 Napoléon BONAPARTE 1127933123568 Le 31/08/2023 Prescriptions relatives au traitement de l'affection de longue durée reconnue (liste ou bors liste (AFFECTION EXONÉRANTE V Prescriptions SANS RAPPORT avec l'affection de langue durée (MALADIES INTERCURRENTES) Oeil droit {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration} TRAITEMENT A RENOUVELER PENDANT {PatternPrescriptions.DrugDuration} Quiconque se rend coupable de fraude ou de fausse déclaration est passible de pénalités financières, d'amende evou d'emprisonnement (articles 313-1, 441-1 441-6 du Code pénal, articles L.114-13 et L. 162-1-14 da Code de la sécurité sociale). S3321",

        $"Docteur Jean-Jacques Fraslin Nº AM: N° RPPS: Spécialiste en médecine générale 15 Rue de la Chapelle - 44340 Bouguenais 441045549 10002519212 jean-jacques.fraslin@medecin.mssante.fr Le 26 nov. 2022 Né(e) le 19/04/2002 BONAPARTE Napoléon {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} {PatternPrescriptions.DrugFrequency}, {PatternPrescriptions.DrugFrequency} et {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration} Ne pas dépasser 3 grammes par 24 heures. {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} dans chaque narine, {PatternPrescriptions.DrugFrequency}. La durée maximale du traitement est de {PatternPrescriptions.DrugDuration}.. {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration} Jean-Jacques Fraslin 3 1/1",

        $"Docteur GUERRERO Maria Eugenia Spécialiste en Médecine Générale à Alicante 17. rue Docteur Leveille 37350 LE GRAND PRESSIGNY Consultations sur Rendez-Vous Tél: 02 47 19 08 74 Fermé le Jeudi NAM: 37 1008905 10101200701 15/12/2022 Monsieur BONAPARTE Napoléon 1) {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} par {PatternPrescriptions.DrugFrequency} au début des repas dans un demi-verre d'eam pendant {PatternPrescriptions.DrugDuration} {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration}. a commencer avec 3 comp le ler jour. {PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} par {PatternPrescriptions.DrugFrequency} selon besoin, en espaçant les prises de 4h mummum. Maximum 3 comprimés par jour. A dissoudre complétement dans un verre d'eau 1 boîte Maria Eugenia GUERRERO 2) 3) Membre d'une Association agréée, le règlement des honoraires par chèque est accepté.",

        $"{PatternPrescriptions.Drug} {PatternPrescriptions.DrugQuantity} {PatternPrescriptions.DrugForm} {PatternPrescriptions.DrugFrequency} {PatternPrescriptions.DrugFrequency} pendant {PatternPrescriptions.DrugDuration}",
    };

    public string[] GetPrescription()
    {
        Random random = new Random();
        int index = random.Next(Prescription.Count);
        return Prescription[index].Split(' ');
    }
}