name: medicapptoolsdatasets
license: EUPL-1.2
summary: MedicAppToolsDatasets
description: |
  Usage:
      medicapptoolsdatasets [options]

  Options:
      -m, --model <model>: Model to use - ai or dataset
      -d, --dataset <dataset>: Dataset to use - CIS_bdpm, CIS_COMPO_bdpm, CIS_CIP_bdpm, CIS_GENER_bdpm, CIS_HAS_SMR_bdpm, CIS_HAS_ASMR_bdpm, CIS_InfoImportantes, CIS_CPD_bdpm, HAS_LiensPageCT_bdpm, all
      --merge: Merge datasets
      -o, --outputDir <outputDir>: Output directory
      -u, --outputUrl <outputUrl>: Output URL
      -s, --sentenceCount <sentenceCount>: Number of sentences to generate
      -i, --input <input>: Input file
      --version: Show version information
      -?, -h, --help: Show help and usage information
base: core22
grade: stable
confinement: strict
version: git

architectures:
  - build-on: amd64
    build-for: amd64

apps:
  medicapptoolsdatasets:
    command: MedicAppToolsDatasets
    plugs: [home, network, network-bind]

parts:
  medicapptoolsdatasets:
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: .
    source-type: git
    build-packages:
      - dotnet-sdk-8.0
      - git
      - sed
    stage-packages:
      - libicu70

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    priority: always
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/ubuntu/22.04/prod